use crate::plan::types::{PlanStep, TestPlan};
use crate::runner::backends::beam::env;

/// Generate a complete ExUnit test module for a test plan.
pub fn generate_exunit_file(plan: &TestPlan) -> String {
    let module_name = env::generated_module_name(&plan.plan.name);
    let mut out = String::with_capacity(1024);

    out.push_str("# Auto-generated by TAST — do not edit\n");
    out.push_str(&format!("# Plan: {}\n\n", plan.plan.name));
    out.push_str(&format!("defmodule {module_name}Test do\n"));
    out.push_str("  use ExUnit.Case\n\n");
    out.push_str("  @moduletag :tast_generated\n");

    for step in &plan.steps {
        out.push('\n');
        out.push_str(&generate_test_block(step));
    }

    out.push_str("end\n");
    out
}

/// Generate a single ExUnit test block for a plan step.
pub fn generate_test_block(step: &PlanStep) -> String {
    let node_name = &step.node;
    let description = step
        .description
        .as_deref()
        .unwrap_or("test step")
        .to_lowercase();

    let mut out = String::with_capacity(512);

    out.push_str(&format!("  describe \"{node_name}\" do\n"));
    out.push_str(&format!("    test \"{description}\" do\n"));

    // Input reads from upstream steps.
    if !step.inputs.is_empty() {
        out.push_str("      # --- Inputs ---\n");
        for input in &step.inputs {
            out.push_str(&format!(
                "      {} = TastHelper.tast_input(\"{}\")\n",
                input.field, input.field
            ));
        }
        out.push('\n');
    }

    // Preconditions (given).
    for entry in &step.preconditions {
        out.push_str(&format!(
            "      # --- {} ---\n",
            capitalize_step_type(&entry.step_type)
        ));
        out.push_str(&format!("      # {}\n", entry.text));

        if !entry.data.is_empty() {
            out.push_str(&generate_data_setup(&entry.data));
        }

        out.push('\n');
    }

    // Actions (when).
    for entry in &step.actions {
        out.push_str(&format!(
            "      # --- {} ---\n",
            capitalize_step_type(&entry.step_type)
        ));
        out.push_str(&format!("      # {}\n", entry.text));
        out.push_str("      # TODO: Implement action\n\n");
    }

    // Assertions (then).
    for entry in &step.assertions {
        out.push_str(&format!(
            "      # --- {} ---\n",
            capitalize_step_type(&entry.step_type)
        ));
        out.push_str(&format!("      # {}\n", entry.text));
        out.push_str("      # TODO: Implement assertion\n\n");
    }

    // Output hint.
    if !step.outputs.is_empty() {
        out.push_str("      # --- Output ---\n");
        let fields: Vec<String> = step.outputs.iter().map(|f| format!("{f}: {f}")).collect();
        out.push_str(&format!(
            "      # TastHelper.tast_output(%{{{}}})\n",
            fields.join(", ")
        ));
        out.push('\n');
    }

    out.push_str("    end\n");
    out.push_str("  end\n");
    out
}

/// Generate the TastHelper module with TAST_OUTPUT/TAST_INPUT utilities.
pub fn generate_helper_module() -> String {
    r#"# Auto-generated by TAST — do not edit
defmodule TastHelper do
  @moduledoc false

  def tast_output(data) when is_map(data) do
    IO.puts("TAST_OUTPUT:#{Jason.encode!(data)}")
  end

  def tast_input(key) do
    System.get_env("TAST_INPUT_#{String.upcase(to_string(key))}")
  end
end
"#
    .to_owned()
}

/// Generate Elixir data setup code from step data fields.
///
/// Produces an Elixir map assignment like:
/// ```elixir
/// data = %{
///   email: "test@example.com",
///   password: "secure123"
/// }
/// ```
pub fn generate_data_setup(data: &[(String, String)]) -> String {
    if data.is_empty() {
        return String::new();
    }

    let mut out = String::new();
    out.push_str("      data = %{\n");
    for (i, (key, value)) in data.iter().enumerate() {
        let escaped = elixir_escape(value);
        let comma = if i < data.len() - 1 { "," } else { "" };
        out.push_str(&format!("        {key}: \"{escaped}\"{comma}\n"));
    }
    out.push_str("      }\n");
    out
}

/// Generate input reading code from resolved input field names.
pub fn generate_input_reads(inputs: &[String]) -> String {
    let mut out = String::new();
    for input in inputs {
        out.push_str(&format!(
            "      {input} = TastHelper.tast_input(\"{input}\")\n"
        ));
    }
    out
}

/// Escape a string for safe embedding in an Elixir double-quoted string.
pub fn elixir_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            '#' => out.push_str("\\#"), // Prevent interpolation injection.
            _ => out.push(ch),
        }
    }
    out
}

fn capitalize_step_type(step_type: &str) -> String {
    let mut chars = step_type.chars();
    match chars.next() {
        None => String::new(),
        Some(c) => c.to_uppercase().to_string() + chars.as_str(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::plan::types::{InputEntry, PlanMetadata, StepEntry};
    use std::collections::HashMap;

    fn make_plan(name: &str, steps: Vec<PlanStep>) -> TestPlan {
        TestPlan {
            plan: PlanMetadata {
                name: name.to_owned(),
                traversal: "topological".to_owned(),
                nodes_total: steps.len(),
                edges_total: 0,
            },
            config: HashMap::new(),
            steps,
        }
    }

    fn make_step(node: &str) -> PlanStep {
        PlanStep {
            order: 1,
            node: node.to_owned(),
            description: Some(format!("test {}", node.to_lowercase())),
            tags: vec![],
            depends_on: vec![],
            preconditions: vec![],
            actions: vec![],
            assertions: vec![],
            inputs: vec![],
            outputs: vec![],
            config: HashMap::new(),
        }
    }

    fn make_entry(step_type: &str, text: &str) -> StepEntry {
        StepEntry {
            step_type: step_type.to_owned(),
            text: text.to_owned(),
            data: vec![],
            parameters: vec![],
        }
    }

    #[test]
    fn generate_exunit_file_header() {
        let plan = make_plan("Auth", vec![make_step("Login")]);
        let output = generate_exunit_file(&plan);
        assert!(output.starts_with("# Auto-generated by TAST"));
        assert!(output.contains("# Plan: Auth"));
    }

    #[test]
    fn generate_exunit_file_module_name() {
        let plan = make_plan("UserAuthentication", vec![make_step("Login")]);
        let output = generate_exunit_file(&plan);
        assert!(output.contains("defmodule TastGenUserAuthenticationTest do"));
    }

    #[test]
    fn generate_exunit_file_uses_exunit_case() {
        let plan = make_plan("Auth", vec![make_step("Login")]);
        let output = generate_exunit_file(&plan);
        assert!(output.contains("use ExUnit.Case"));
    }

    #[test]
    fn generate_exunit_file_has_moduletag() {
        let plan = make_plan("Auth", vec![make_step("Login")]);
        let output = generate_exunit_file(&plan);
        assert!(output.contains("@moduletag :tast_generated"));
    }

    #[test]
    fn generate_exunit_file_single_step() {
        let plan = make_plan("Auth", vec![make_step("Login")]);
        let output = generate_exunit_file(&plan);
        assert!(output.contains("describe \"Login\""));
        assert!(output.contains("test \"test login\""));
    }

    #[test]
    fn generate_exunit_file_multiple_steps() {
        let plan = make_plan("Auth", vec![make_step("Register"), make_step("Login")]);
        let output = generate_exunit_file(&plan);
        assert!(output.contains("describe \"Register\""));
        assert!(output.contains("describe \"Login\""));
    }

    #[test]
    fn generate_exunit_file_ends_with_end() {
        let plan = make_plan("Auth", vec![make_step("Login")]);
        let output = generate_exunit_file(&plan);
        assert!(output.trim_end().ends_with("end"));
    }

    #[test]
    fn generate_test_block_given_with_data() {
        let mut step = make_step("Register");
        step.preconditions.push(StepEntry {
            step_type: "given".to_owned(),
            text: "a user with credentials".to_owned(),
            data: vec![
                ("email".to_owned(), "test@example.com".to_owned()),
                ("password".to_owned(), "secure123".to_owned()),
            ],
            parameters: vec![],
        });

        let output = generate_test_block(&step);
        assert!(output.contains("# --- Given ---"));
        assert!(output.contains("# a user with credentials"));
        assert!(output.contains("data = %{"));
        assert!(output.contains("email: \"test@example.com\""));
        assert!(output.contains("password: \"secure123\""));
    }

    #[test]
    fn generate_test_block_when_action() {
        let mut step = make_step("Register");
        step.actions
            .push(make_entry("when", "the user submits the form"));

        let output = generate_test_block(&step);
        assert!(output.contains("# --- When ---"));
        assert!(output.contains("# the user submits the form"));
        assert!(output.contains("# TODO: Implement action"));
    }

    #[test]
    fn generate_test_block_then_assertion() {
        let mut step = make_step("Register");
        step.assertions
            .push(make_entry("then", "the account is created"));

        let output = generate_test_block(&step);
        assert!(output.contains("# --- Then ---"));
        assert!(output.contains("# the account is created"));
        assert!(output.contains("# TODO: Implement assertion"));
    }

    #[test]
    fn generate_test_block_and_but_steps() {
        let mut step = make_step("Register");
        step.assertions
            .push(make_entry("then", "the account is created"));
        step.assertions
            .push(make_entry("and", "a confirmation email is sent"));
        step.assertions
            .push(make_entry("but", "no welcome bonus is given"));

        let output = generate_test_block(&step);
        assert!(output.contains("# --- Then ---"));
        assert!(output.contains("# --- And ---"));
        assert!(output.contains("# --- But ---"));
    }

    #[test]
    fn generate_test_block_with_inputs() {
        let mut step = make_step("Login");
        step.inputs.push(InputEntry {
            field: "user_id".to_owned(),
            from: "Register".to_owned(),
        });
        step.inputs.push(InputEntry {
            field: "email".to_owned(),
            from: "Register".to_owned(),
        });

        let output = generate_test_block(&step);
        assert!(output.contains("# --- Inputs ---"));
        assert!(output.contains("user_id = TastHelper.tast_input(\"user_id\")"));
        assert!(output.contains("email = TastHelper.tast_input(\"email\")"));
    }

    #[test]
    fn generate_test_block_with_outputs() {
        let mut step = make_step("Login");
        step.outputs = vec!["auth_token".to_owned(), "session_id".to_owned()];

        let output = generate_test_block(&step);
        assert!(output.contains("# --- Output ---"));
        assert!(output.contains("TastHelper.tast_output"));
        assert!(output.contains("auth_token"));
        assert!(output.contains("session_id"));
    }

    #[test]
    fn generate_helper_module_has_tast_output() {
        let helper = generate_helper_module();
        assert!(helper.contains("def tast_output(data)"));
        assert!(helper.contains("TAST_OUTPUT:"));
        assert!(helper.contains("Jason.encode!"));
    }

    #[test]
    fn generate_helper_module_has_tast_input() {
        let helper = generate_helper_module();
        assert!(helper.contains("def tast_input(key)"));
        assert!(helper.contains("System.get_env"));
        assert!(helper.contains("TAST_INPUT_"));
    }

    #[test]
    fn generate_helper_module_is_module() {
        let helper = generate_helper_module();
        assert!(helper.contains("defmodule TastHelper do"));
        assert!(helper.trim_end().ends_with("end"));
    }

    #[test]
    fn generate_data_setup_single_field() {
        let data = vec![("email".to_owned(), "test@example.com".to_owned())];
        let output = generate_data_setup(&data);
        assert!(output.contains("data = %{"));
        assert!(output.contains("email: \"test@example.com\""));
    }

    #[test]
    fn generate_data_setup_multiple_fields() {
        let data = vec![
            ("email".to_owned(), "test@example.com".to_owned()),
            ("password".to_owned(), "secret".to_owned()),
        ];
        let output = generate_data_setup(&data);
        assert!(output.contains("email: \"test@example.com\","));
        assert!(output.contains("password: \"secret\""));
        // Last field should NOT have a trailing comma.
        assert!(!output.contains("secret\","));
    }

    #[test]
    fn generate_data_setup_empty() {
        assert!(generate_data_setup(&[]).is_empty());
    }

    #[test]
    fn generate_input_reads_single() {
        let inputs = vec!["user_id".to_owned()];
        let output = generate_input_reads(&inputs);
        assert!(output.contains("user_id = TastHelper.tast_input(\"user_id\")"));
    }

    #[test]
    fn generate_input_reads_multiple() {
        let inputs = vec!["user_id".to_owned(), "email".to_owned()];
        let output = generate_input_reads(&inputs);
        assert!(output.contains("user_id = TastHelper.tast_input(\"user_id\")"));
        assert!(output.contains("email = TastHelper.tast_input(\"email\")"));
    }

    #[test]
    fn elixir_escape_quotes() {
        assert_eq!(elixir_escape(r#"say "hello""#), r#"say \"hello\""#);
    }

    #[test]
    fn elixir_escape_backslash() {
        assert_eq!(elixir_escape(r"path\to\file"), r"path\\to\\file");
    }

    #[test]
    fn elixir_escape_interpolation() {
        assert_eq!(elixir_escape("#{var}"), "\\#{var}");
    }

    #[test]
    fn elixir_escape_newline() {
        assert_eq!(elixir_escape("line1\nline2"), "line1\\nline2");
    }

    #[test]
    fn elixir_escape_plain_text() {
        assert_eq!(elixir_escape("hello world"), "hello world");
    }
}
