use crate::plan::types::{PlanStep, TestPlan};
use crate::runner::backends::beam::env;

/// Generate a complete Gleam test module for a test plan.
pub fn generate_gleam_test_file(plan: &TestPlan) -> String {
    let mut out = String::with_capacity(1024);

    out.push_str("// Auto-generated by TAST — do not edit\n");
    out.push_str(&format!("// Plan: {}\n\n", plan.plan.name));

    // Imports.
    out.push_str("import gleam/dict\n");
    out.push_str("import gleam/erlang/os\n");
    out.push_str("import gleam/io\n");
    out.push_str("import tast_generated/tast_helper\n\n");

    for step in &plan.steps {
        out.push_str(&generate_test_function(step));
        out.push('\n');
    }

    out
}

/// Generate a single Gleam test function for a plan step.
///
/// Gleam test functions must be public and end with `_test`.
pub fn generate_test_function(step: &PlanStep) -> String {
    let fn_name = format!("{}_test", env::to_beam_name(&step.node));
    let description = step
        .description
        .as_deref()
        .unwrap_or("test step")
        .to_lowercase();

    let mut out = String::with_capacity(512);

    out.push_str(&format!("pub fn {fn_name}() {{\n"));
    out.push_str(&format!("  // Step {}: {}\n", step.order, step.node));
    out.push_str(&format!("  // \"{description}\"\n"));

    // Input reads from upstream steps.
    if !step.inputs.is_empty() {
        out.push('\n');
        out.push_str("  // --- Inputs ---\n");
        for input in &step.inputs {
            out.push_str(&format!(
                "  let {} = tast_helper.tast_input(\"{}\")\n",
                input.field, input.field
            ));
        }
    }

    // Preconditions (given).
    for entry in &step.preconditions {
        out.push('\n');
        out.push_str(&format!(
            "  // --- {} ---\n",
            capitalize_step_type(&entry.step_type)
        ));
        out.push_str(&format!("  // {}\n", entry.text));

        if !entry.data.is_empty() {
            out.push_str(&generate_data_bindings(&entry.data));
        }
    }

    // Actions (when).
    for entry in &step.actions {
        out.push('\n');
        out.push_str(&format!(
            "  // --- {} ---\n",
            capitalize_step_type(&entry.step_type)
        ));
        out.push_str(&format!("  // {}\n", entry.text));
        out.push_str("  // TODO: Implement action\n");
    }

    // Assertions (then).
    for entry in &step.assertions {
        out.push('\n');
        out.push_str(&format!(
            "  // --- {} ---\n",
            capitalize_step_type(&entry.step_type)
        ));
        out.push_str(&format!("  // {}\n", entry.text));
        out.push_str("  // TODO: Implement assertion\n");
    }

    // Output hint.
    if !step.outputs.is_empty() {
        out.push('\n');
        out.push_str("  // --- Output ---\n");
        let fields: Vec<String> = step
            .outputs
            .iter()
            .map(|f| format!("#(\"{f}\", {f})"))
            .collect();
        out.push_str(&format!(
            "  // tast_helper.tast_output(dict.from_list([{}]))\n",
            fields.join(", ")
        ));
    }

    out.push_str("}\n");
    out
}

/// Generate the TastHelper module with TAST_OUTPUT/TAST_INPUT utilities.
pub fn generate_helper_module() -> String {
    r#"// Auto-generated by TAST — do not edit
import gleam/dict.{type Dict}
import gleam/erlang/os
import gleam/io
import gleam/json
import gleam/list
import gleam/string

pub fn tast_output(data: Dict(String, String)) -> Nil {
  let json_str =
    data
    |> dict.to_list
    |> list.map(fn(pair) {
      let #(key, value) = pair
      #(key, json.string(value))
    })
    |> json.object
    |> json.to_string
  io.println("TAST_OUTPUT:" <> json_str)
}

pub fn tast_input(key: String) -> String {
  let env_key = "TAST_INPUT_" <> string.uppercase(key)
  case os.get_env(env_key) {
    Ok(value) -> value
    Error(_) -> ""
  }
}
"#
    .to_owned()
}

/// Generate Gleam data binding code from step data fields.
///
/// Produces:
/// ```gleam
/// let data = dict.from_list([
///   #("email", "test@example.com"),
///   #("password", "secure123"),
/// ])
/// ```
pub fn generate_data_bindings(data: &[(String, String)]) -> String {
    if data.is_empty() {
        return String::new();
    }

    let mut out = String::new();
    out.push_str("  let data = dict.from_list([\n");
    for (key, value) in data {
        let escaped = gleam_escape(value);
        out.push_str(&format!("    #(\"{key}\", \"{escaped}\"),\n"));
    }
    out.push_str("  ])\n");
    out
}

/// Escape a string for safe embedding in a Gleam double-quoted string.
pub fn gleam_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            _ => out.push(ch),
        }
    }
    out
}

fn capitalize_step_type(step_type: &str) -> String {
    let mut chars = step_type.chars();
    match chars.next() {
        None => String::new(),
        Some(c) => c.to_uppercase().to_string() + chars.as_str(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::plan::types::{InputEntry, PlanMetadata, StepEntry};
    use std::collections::HashMap;

    fn make_plan(name: &str, steps: Vec<PlanStep>) -> TestPlan {
        TestPlan {
            plan: PlanMetadata {
                name: name.to_owned(),
                traversal: "topological".to_owned(),
                nodes_total: steps.len(),
                edges_total: 0,
            },
            config: HashMap::new(),
            steps,
        }
    }

    fn make_step(node: &str, order: usize) -> PlanStep {
        PlanStep {
            order,
            node: node.to_owned(),
            description: Some(format!("test {}", node.to_lowercase())),
            tags: vec![],
            depends_on: vec![],
            preconditions: vec![],
            actions: vec![],
            assertions: vec![],
            inputs: vec![],
            outputs: vec![],
            config: HashMap::new(),
        }
    }

    fn make_entry(step_type: &str, text: &str) -> StepEntry {
        StepEntry {
            step_type: step_type.to_owned(),
            text: text.to_owned(),
            data: vec![],
            parameters: vec![],
        }
    }

    #[test]
    fn generate_gleam_test_file_header() {
        let plan = make_plan("Auth", vec![make_step("Login", 1)]);
        let output = generate_gleam_test_file(&plan);
        assert!(output.starts_with("// Auto-generated by TAST"));
        assert!(output.contains("// Plan: Auth"));
    }

    #[test]
    fn generate_gleam_test_file_imports() {
        let plan = make_plan("Auth", vec![make_step("Login", 1)]);
        let output = generate_gleam_test_file(&plan);
        assert!(output.contains("import gleam/dict"));
        assert!(output.contains("import tast_generated/tast_helper"));
    }

    #[test]
    fn generate_gleam_test_file_single_step() {
        let plan = make_plan("Auth", vec![make_step("Login", 1)]);
        let output = generate_gleam_test_file(&plan);
        assert!(output.contains("pub fn login_test()"));
    }

    #[test]
    fn generate_gleam_test_file_multiple_steps() {
        let plan = make_plan(
            "Auth",
            vec![make_step("Register", 1), make_step("Login", 2)],
        );
        let output = generate_gleam_test_file(&plan);
        assert!(output.contains("pub fn register_test()"));
        assert!(output.contains("pub fn login_test()"));
    }

    #[test]
    fn generate_test_function_name_from_node() {
        let step = make_step("RegisterUser", 1);
        let output = generate_test_function(&step);
        assert!(output.contains("pub fn register_user_test()"));
    }

    #[test]
    fn generate_test_function_given_with_data() {
        let mut step = make_step("Register", 1);
        step.preconditions.push(StepEntry {
            step_type: "given".to_owned(),
            text: "a user with credentials".to_owned(),
            data: vec![
                ("email".to_owned(), "test@example.com".to_owned()),
                ("password".to_owned(), "secure123".to_owned()),
            ],
            parameters: vec![],
        });

        let output = generate_test_function(&step);
        assert!(output.contains("// --- Given ---"));
        assert!(output.contains("// a user with credentials"));
        assert!(output.contains("dict.from_list"));
        assert!(output.contains("#(\"email\", \"test@example.com\")"));
        assert!(output.contains("#(\"password\", \"secure123\")"));
    }

    #[test]
    fn generate_test_function_when_action() {
        let mut step = make_step("Register", 1);
        step.actions
            .push(make_entry("when", "the user submits the form"));

        let output = generate_test_function(&step);
        assert!(output.contains("// --- When ---"));
        assert!(output.contains("// the user submits the form"));
        assert!(output.contains("// TODO: Implement action"));
    }

    #[test]
    fn generate_test_function_then_assertion() {
        let mut step = make_step("Register", 1);
        step.assertions
            .push(make_entry("then", "the account is created"));

        let output = generate_test_function(&step);
        assert!(output.contains("// --- Then ---"));
        assert!(output.contains("// the account is created"));
        assert!(output.contains("// TODO: Implement assertion"));
    }

    #[test]
    fn generate_test_function_with_inputs() {
        let mut step = make_step("Login", 2);
        step.inputs.push(InputEntry {
            field: "user_id".to_owned(),
            from: "Register".to_owned(),
        });
        step.inputs.push(InputEntry {
            field: "email".to_owned(),
            from: "Register".to_owned(),
        });

        let output = generate_test_function(&step);
        assert!(output.contains("// --- Inputs ---"));
        assert!(output.contains("tast_helper.tast_input(\"user_id\")"));
        assert!(output.contains("tast_helper.tast_input(\"email\")"));
    }

    #[test]
    fn generate_test_function_with_outputs() {
        let mut step = make_step("Login", 1);
        step.outputs = vec!["auth_token".to_owned(), "session_id".to_owned()];

        let output = generate_test_function(&step);
        assert!(output.contains("// --- Output ---"));
        assert!(output.contains("tast_helper.tast_output"));
        assert!(output.contains("auth_token"));
        assert!(output.contains("session_id"));
    }

    #[test]
    fn generate_helper_module_has_tast_output() {
        let helper = generate_helper_module();
        assert!(helper.contains("pub fn tast_output"));
        assert!(helper.contains("TAST_OUTPUT:"));
        assert!(helper.contains("json.to_string"));
    }

    #[test]
    fn generate_helper_module_has_tast_input() {
        let helper = generate_helper_module();
        assert!(helper.contains("pub fn tast_input"));
        assert!(helper.contains("os.get_env"));
        assert!(helper.contains("TAST_INPUT_"));
    }

    #[test]
    fn generate_data_bindings_single() {
        let data = vec![("email".to_owned(), "test@example.com".to_owned())];
        let output = generate_data_bindings(&data);
        assert!(output.contains("dict.from_list"));
        assert!(output.contains("#(\"email\", \"test@example.com\")"));
    }

    #[test]
    fn generate_data_bindings_multiple() {
        let data = vec![
            ("email".to_owned(), "test@example.com".to_owned()),
            ("password".to_owned(), "secret".to_owned()),
        ];
        let output = generate_data_bindings(&data);
        assert!(output.contains("#(\"email\", \"test@example.com\")"));
        assert!(output.contains("#(\"password\", \"secret\")"));
    }

    #[test]
    fn generate_data_bindings_empty() {
        assert!(generate_data_bindings(&[]).is_empty());
    }

    #[test]
    fn gleam_escape_quotes() {
        assert_eq!(gleam_escape(r#"say "hello""#), r#"say \"hello\""#);
    }

    #[test]
    fn gleam_escape_backslash() {
        assert_eq!(gleam_escape(r"path\to\file"), r"path\\to\\file");
    }

    #[test]
    fn gleam_escape_newline() {
        assert_eq!(gleam_escape("line1\nline2"), "line1\\nline2");
    }

    #[test]
    fn gleam_escape_plain_text() {
        assert_eq!(gleam_escape("hello world"), "hello world");
    }
}
