use crate::plan::types::{PlanStep, TestPlan};
use crate::runner::backends::beam::env;

/// Generate a complete EUnit test module for a test plan.
pub fn generate_eunit_file(plan: &TestPlan) -> String {
    let module_name = eunit_module_name(&plan.plan.name);
    let mut out = String::with_capacity(1024);

    out.push_str("%% Auto-generated by TAST — do not edit\n");
    out.push_str(&format!("%% Plan: {}\n", plan.plan.name));
    out.push_str(&format!("-module({module_name}).\n"));
    out.push_str("-include_lib(\"eunit/include/eunit.hrl\").\n\n");

    for step in &plan.steps {
        out.push_str(&generate_test_function(step));
        out.push('\n');
    }

    out
}

/// Generate a single EUnit test function for a plan step.
///
/// EUnit auto-discovers functions ending in `_test`.
pub fn generate_test_function(step: &PlanStep) -> String {
    let fn_name = format!("{}_test", env::to_beam_name(&step.node));
    let description = step
        .description
        .as_deref()
        .unwrap_or("test step")
        .to_lowercase();

    let mut out = String::with_capacity(512);

    out.push_str(&format!("%% Step {}: {}\n", step.order, step.node));
    out.push_str(&format!("%% \"{description}\"\n"));
    out.push_str(&format!("{fn_name}() ->\n"));

    // Input reads from upstream steps.
    if !step.inputs.is_empty() {
        out.push_str("    %% --- Inputs ---\n");
        for input in &step.inputs {
            let var_name = erlang_var_name(&input.field);
            out.push_str(&format!(
                "    {var_name} = tast_helper:tast_input(\"{}\"),\n",
                input.field
            ));
        }
        out.push('\n');
    }

    // Preconditions (given).
    for entry in &step.preconditions {
        out.push_str(&format!(
            "    %% --- {} ---\n",
            capitalize_step_type(&entry.step_type)
        ));
        out.push_str(&format!("    %% {}\n", entry.text));

        if !entry.data.is_empty() {
            out.push_str(&generate_data_map(&entry.data));
        }

        out.push('\n');
    }

    // Actions (when).
    for entry in &step.actions {
        out.push_str(&format!(
            "    %% --- {} ---\n",
            capitalize_step_type(&entry.step_type)
        ));
        out.push_str(&format!("    %% {}\n", entry.text));
        out.push_str("    %% TODO: Implement action\n\n");
    }

    // Assertions (then).
    for entry in &step.assertions {
        out.push_str(&format!(
            "    %% --- {} ---\n",
            capitalize_step_type(&entry.step_type)
        ));
        out.push_str(&format!("    %% {}\n", entry.text));
        out.push_str("    %% TODO: Implement assertion\n\n");
    }

    // Output hint.
    if !step.outputs.is_empty() {
        out.push_str("    %% --- Output ---\n");
        let fields: Vec<String> = step
            .outputs
            .iter()
            .map(|f| format!("<<\"{f}\">> => {}", erlang_var_name(f)))
            .collect();
        out.push_str(&format!(
            "    %% tast_helper:tast_output(#{{{}}})\n\n",
            fields.join(", ")
        ));
    }

    out.push_str("    ok.\n");
    out
}

/// Generate the tast_helper module with TAST_OUTPUT/TAST_INPUT utilities.
pub fn generate_helper_module() -> String {
    r#"%% Auto-generated by TAST — do not edit
-module(tast_helper).
-export([tast_output/1, tast_input/1]).

tast_output(Data) when is_map(Data) ->
    Pairs = maps:fold(fun(K, V, Acc) ->
        [io_lib:format("\"~s\":\"~s\"", [K, V]) | Acc]
    end, [], Data),
    Json = io_lib:format("{~s}", [string:join(lists:reverse(Pairs), ",")]),
    io:format("TAST_OUTPUT:~s~n", [Json]).

tast_input(Key) ->
    EnvKey = "TAST_INPUT_" ++ string:to_upper(Key),
    case os:getenv(EnvKey) of
        false -> "";
        Value -> Value
    end.
"#
    .to_owned()
}

/// Generate Erlang map construction from step data fields.
///
/// Produces:
/// ```erlang
/// Data = #{
///   <<"email">> => <<"test@example.com">>,
///   <<"password">> => <<"secure123">>
/// }
/// ```
pub fn generate_data_map(data: &[(String, String)]) -> String {
    if data.is_empty() {
        return String::new();
    }

    let mut out = String::new();
    out.push_str("    Data = #{\n");
    for (i, (key, value)) in data.iter().enumerate() {
        let escaped = erlang_escape(value);
        let comma = if i < data.len() - 1 { "," } else { "" };
        out.push_str(&format!(
            "        <<\"{key}\">> => <<\"{escaped}\">>{comma}\n"
        ));
    }
    out.push_str("    },\n");
    out
}

/// Escape a string for safe embedding in an Erlang binary string (`<<"...">>`).
pub fn erlang_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            _ => out.push(ch),
        }
    }
    out
}

/// Convert a field name to an Erlang variable name (CamelCase, starts uppercase).
///
/// `"user_id"` → `"UserId"`
/// `"email"` → `"Email"`
fn erlang_var_name(field: &str) -> String {
    field
        .split('_')
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                None => String::new(),
                Some(c) => c.to_uppercase().to_string() + chars.as_str(),
            }
        })
        .collect()
}

/// Derive the EUnit module name from a plan name.
///
/// `"UserAuthentication"` → `"tast_gen_user_authentication"`
fn eunit_module_name(plan_name: &str) -> String {
    format!("tast_gen_{}", env::to_beam_name(plan_name))
}

fn capitalize_step_type(step_type: &str) -> String {
    let mut chars = step_type.chars();
    match chars.next() {
        None => String::new(),
        Some(c) => c.to_uppercase().to_string() + chars.as_str(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::plan::types::{InputEntry, PlanMetadata, StepEntry};
    use std::collections::HashMap;

    fn make_plan(name: &str, steps: Vec<PlanStep>) -> TestPlan {
        TestPlan {
            plan: PlanMetadata {
                name: name.to_owned(),
                traversal: "topological".to_owned(),
                nodes_total: steps.len(),
                edges_total: 0,
            },
            config: HashMap::new(),
            steps,
        }
    }

    fn make_step(node: &str, order: usize) -> PlanStep {
        PlanStep {
            order,
            node: node.to_owned(),
            description: Some(format!("test {}", node.to_lowercase())),
            tags: vec![],
            depends_on: vec![],
            preconditions: vec![],
            actions: vec![],
            assertions: vec![],
            inputs: vec![],
            outputs: vec![],
            config: HashMap::new(),
        }
    }

    fn make_entry(step_type: &str, text: &str) -> StepEntry {
        StepEntry {
            step_type: step_type.to_owned(),
            text: text.to_owned(),
            data: vec![],
            parameters: vec![],
        }
    }

    #[test]
    fn generate_eunit_file_module_declaration() {
        let plan = make_plan("UserAuthentication", vec![make_step("Login", 1)]);
        let output = generate_eunit_file(&plan);
        assert!(output.contains("-module(tast_gen_user_authentication)."));
    }

    #[test]
    fn generate_eunit_file_eunit_include() {
        let plan = make_plan("Auth", vec![make_step("Login", 1)]);
        let output = generate_eunit_file(&plan);
        assert!(output.contains("-include_lib(\"eunit/include/eunit.hrl\")."));
    }

    #[test]
    fn generate_eunit_file_header() {
        let plan = make_plan("Auth", vec![make_step("Login", 1)]);
        let output = generate_eunit_file(&plan);
        assert!(output.starts_with("%% Auto-generated by TAST"));
        assert!(output.contains("%% Plan: Auth"));
    }

    #[test]
    fn generate_eunit_file_single_step() {
        let plan = make_plan("Auth", vec![make_step("Login", 1)]);
        let output = generate_eunit_file(&plan);
        assert!(output.contains("login_test() ->"));
    }

    #[test]
    fn generate_eunit_file_multiple_steps() {
        let plan = make_plan(
            "Auth",
            vec![make_step("Register", 1), make_step("Login", 2)],
        );
        let output = generate_eunit_file(&plan);
        assert!(output.contains("register_test() ->"));
        assert!(output.contains("login_test() ->"));
    }

    #[test]
    fn generate_test_function_name_from_node() {
        let step = make_step("RegisterUser", 1);
        let output = generate_test_function(&step);
        assert!(output.contains("register_user_test() ->"));
    }

    #[test]
    fn generate_test_function_given_with_data() {
        let mut step = make_step("Register", 1);
        step.preconditions.push(StepEntry {
            step_type: "given".to_owned(),
            text: "a user with credentials".to_owned(),
            data: vec![
                ("email".to_owned(), "test@example.com".to_owned()),
                ("password".to_owned(), "secure123".to_owned()),
            ],
            parameters: vec![],
        });

        let output = generate_test_function(&step);
        assert!(output.contains("%% --- Given ---"));
        assert!(output.contains("%% a user with credentials"));
        assert!(output.contains("Data = #{"));
        assert!(output.contains("<<\"email\">> => <<\"test@example.com\">>"));
        assert!(output.contains("<<\"password\">> => <<\"secure123\">>"));
    }

    #[test]
    fn generate_test_function_when_action() {
        let mut step = make_step("Register", 1);
        step.actions
            .push(make_entry("when", "the user submits the form"));

        let output = generate_test_function(&step);
        assert!(output.contains("%% --- When ---"));
        assert!(output.contains("%% the user submits the form"));
        assert!(output.contains("%% TODO: Implement action"));
    }

    #[test]
    fn generate_test_function_then_assertion() {
        let mut step = make_step("Register", 1);
        step.assertions
            .push(make_entry("then", "the account is created"));

        let output = generate_test_function(&step);
        assert!(output.contains("%% --- Then ---"));
        assert!(output.contains("%% the account is created"));
        assert!(output.contains("%% TODO: Implement assertion"));
    }

    #[test]
    fn generate_test_function_with_inputs() {
        let mut step = make_step("Login", 2);
        step.inputs.push(InputEntry {
            field: "user_id".to_owned(),
            from: "Register".to_owned(),
        });
        step.inputs.push(InputEntry {
            field: "email".to_owned(),
            from: "Register".to_owned(),
        });

        let output = generate_test_function(&step);
        assert!(output.contains("%% --- Inputs ---"));
        assert!(output.contains("UserId = tast_helper:tast_input(\"user_id\")"));
        assert!(output.contains("Email = tast_helper:tast_input(\"email\")"));
    }

    #[test]
    fn generate_test_function_with_outputs() {
        let mut step = make_step("Login", 1);
        step.outputs = vec!["auth_token".to_owned(), "session_id".to_owned()];

        let output = generate_test_function(&step);
        assert!(output.contains("%% --- Output ---"));
        assert!(output.contains("tast_helper:tast_output"));
        assert!(output.contains("auth_token"));
        assert!(output.contains("session_id"));
    }

    #[test]
    fn generate_test_function_ends_with_ok() {
        let step = make_step("Login", 1);
        let output = generate_test_function(&step);
        assert!(output.trim_end().ends_with("ok."));
    }

    #[test]
    fn generate_helper_module_has_tast_output() {
        let helper = generate_helper_module();
        assert!(helper.contains("tast_output(Data)"));
        assert!(helper.contains("TAST_OUTPUT:"));
    }

    #[test]
    fn generate_helper_module_has_tast_input() {
        let helper = generate_helper_module();
        assert!(helper.contains("tast_input(Key)"));
        assert!(helper.contains("os:getenv"));
        assert!(helper.contains("TAST_INPUT_"));
    }

    #[test]
    fn generate_helper_module_exports() {
        let helper = generate_helper_module();
        assert!(helper.contains("-module(tast_helper)."));
        assert!(helper.contains("-export([tast_output/1, tast_input/1])."));
    }

    #[test]
    fn generate_data_map_single() {
        let data = vec![("email".to_owned(), "test@example.com".to_owned())];
        let output = generate_data_map(&data);
        assert!(output.contains("Data = #{"));
        assert!(output.contains("<<\"email\">> => <<\"test@example.com\">>"));
    }

    #[test]
    fn generate_data_map_multiple() {
        let data = vec![
            ("email".to_owned(), "test@example.com".to_owned()),
            ("password".to_owned(), "secret".to_owned()),
        ];
        let output = generate_data_map(&data);
        assert!(output.contains("<<\"email\">> => <<\"test@example.com\">>,"));
        assert!(output.contains("<<\"password\">> => <<\"secret\">>"));
        // Last field should NOT have trailing comma.
        assert!(!output.contains("secret\">>,"));
    }

    #[test]
    fn generate_data_map_empty() {
        assert!(generate_data_map(&[]).is_empty());
    }

    #[test]
    fn erlang_escape_quotes() {
        assert_eq!(erlang_escape(r#"say "hello""#), r#"say \"hello\""#);
    }

    #[test]
    fn erlang_escape_backslash() {
        assert_eq!(erlang_escape(r"path\to\file"), r"path\\to\\file");
    }

    #[test]
    fn erlang_escape_newline() {
        assert_eq!(erlang_escape("line1\nline2"), "line1\\nline2");
    }

    #[test]
    fn erlang_escape_plain_text() {
        assert_eq!(erlang_escape("hello world"), "hello world");
    }

    #[test]
    fn erlang_var_name_simple() {
        assert_eq!(erlang_var_name("email"), "Email");
    }

    #[test]
    fn erlang_var_name_underscore() {
        assert_eq!(erlang_var_name("user_id"), "UserId");
    }

    #[test]
    fn eunit_module_name_simple() {
        assert_eq!(eunit_module_name("Auth"), "tast_gen_auth");
    }

    #[test]
    fn eunit_module_name_camel_case() {
        assert_eq!(
            eunit_module_name("UserAuthentication"),
            "tast_gen_user_authentication"
        );
    }
}
