//! End-to-end integration tests for the Gleam backend.
//!
//! These tests validate the full pipeline: programmatic `TestPlan` → GleamBackend →
//! generate harness → verify files → cleanup.
//!
//! Fast tests exercise harness generation, cleanup, and error paths without requiring
//! `gleam` to be installed. Tests that require `gleam` are gated behind a runtime check.

use std::collections::HashMap;

use tast::plan::types::{InputEntry, PlanMetadata, PlanStep, StepEntry, TestPlan};
use tast::runner::backend::TestBackend;
use tast::runner::backends::gleam::GleamBackend;
use tast::runner::context::RunContext;
use tast::runner::result::{StepErrorKind, StepStatus};

// ── Helpers ─────────────────────────────────────────────────

fn make_step(order: usize, node: &str) -> PlanStep {
    PlanStep {
        order,
        node: node.to_string(),
        description: Some(format!("Gleam step: {node}")),
        tags: vec![],
        depends_on: vec![],
        preconditions: vec![StepEntry {
            step_type: "given".into(),
            text: "a test environment".into(),
            data: vec![],
            parameters: vec![],
        }],
        actions: vec![StepEntry {
            step_type: "when".into(),
            text: "the test runs".into(),
            data: vec![],
            parameters: vec![],
        }],
        assertions: vec![StepEntry {
            step_type: "then".into(),
            text: "it succeeds".into(),
            data: vec![],
            parameters: vec![],
        }],
        inputs: vec![],
        outputs: vec![],
        config: HashMap::new(),
    }
}

fn make_plan(name: &str, steps: Vec<PlanStep>) -> TestPlan {
    let node_count = steps.len();
    TestPlan {
        plan: PlanMetadata {
            name: name.to_string(),
            traversal: "topological".to_string(),
            nodes_total: node_count,
            edges_total: 0,
        },
        config: HashMap::new(),
        steps,
    }
}

// ── Harness generation tests ────────────────────────────────

#[test]
fn gleam_e2e_harness_generation_creates_files() {
    let backend = GleamBackend::new();
    let plan = make_plan(
        "AuthFlow",
        vec![make_step(1, "Register"), make_step(2, "Login")],
    );
    let context = RunContext::new("/tmp");

    let harness = backend.generate_harness(&plan, &context).unwrap();

    assert!(harness.entry_point.exists());
    assert_eq!(harness.files.len(), 2);
    for file in &harness.files {
        assert!(file.exists(), "generated file should exist: {file:?}");
    }

    let _ = backend.cleanup(&harness);
}

#[test]
fn gleam_e2e_generated_test_file_contains_gleam_code() {
    let backend = GleamBackend::new();
    let plan = make_plan(
        "Auth",
        vec![make_step(1, "RegisterUser"), make_step(2, "LoginUser")],
    );
    let context = RunContext::new("/tmp");

    let harness = backend.generate_harness(&plan, &context).unwrap();

    let test_path = &harness.files[1];
    let content = std::fs::read_to_string(test_path).unwrap();

    assert!(content.contains("// Auto-generated by TAST"));
    assert!(content.contains("// Plan: Auth"));
    assert!(content.contains("import gleam/dict"));
    assert!(content.contains("import tast_generated/tast_helper"));
    assert!(content.contains("pub fn register_user_test()"));
    assert!(content.contains("pub fn login_user_test()"));
    assert!(content.contains("// --- Given ---"));
    assert!(content.contains("// --- When ---"));
    assert!(content.contains("// --- Then ---"));

    let _ = backend.cleanup(&harness);
}

#[test]
fn gleam_e2e_generated_helper_module() {
    let backend = GleamBackend::new();
    let plan = make_plan("Auth", vec![make_step(1, "Register")]);
    let context = RunContext::new("/tmp");

    let harness = backend.generate_harness(&plan, &context).unwrap();

    let helper_path = &harness.files[0];
    let content = std::fs::read_to_string(helper_path).unwrap();

    assert!(content.contains("pub fn tast_output"));
    assert!(content.contains("pub fn tast_input"));
    assert!(content.contains("TAST_OUTPUT:"));
    assert!(content.contains("TAST_INPUT_"));

    let _ = backend.cleanup(&harness);
}

#[test]
fn gleam_e2e_cleanup_removes_generated_dir() {
    let backend = GleamBackend::new();
    let plan = make_plan("Cleanup", vec![make_step(1, "StepA")]);
    let context = RunContext::new("/tmp");

    let harness = backend.generate_harness(&plan, &context).unwrap();
    let entry = harness.entry_point.clone();
    assert!(entry.exists());

    backend.cleanup(&harness).unwrap();
    assert!(!entry.exists());
}

#[test]
fn gleam_e2e_missing_input_fails() {
    let backend = GleamBackend::new();
    let plan = make_plan("InputTest", vec![make_step(1, "Producer")]);

    let mut step = make_step(2, "Consumer");
    step.inputs.push(InputEntry {
        field: "token".to_string(),
        from: "Producer".to_string(),
    });

    let context = RunContext::new("/tmp");
    let harness = backend.generate_harness(&plan, &context).unwrap();
    let mut ctx = RunContext::new("/tmp");

    let result = backend.execute_step(&step, &harness, &mut ctx).unwrap();

    assert_eq!(result.status, StepStatus::Failed);
    assert_eq!(
        result.error.as_ref().unwrap().kind,
        StepErrorKind::MissingInput
    );

    let _ = backend.cleanup(&harness);
}

#[test]
fn gleam_e2e_spawn_failure_returns_error() {
    let mut backend = GleamBackend::new();
    backend.gleam_command = "nonexistent_gleam_binary_xyz".into();

    let plan = make_plan("SpawnFail", vec![make_step(1, "StepA")]);
    let context = RunContext::new("/tmp");
    let harness = backend.generate_harness(&plan, &context).unwrap();
    let mut ctx = RunContext::new("/tmp");

    let result = backend.execute_step(&plan.steps[0], &harness, &mut ctx);

    assert!(
        result.is_err(),
        "bad gleam binary should return BackendError"
    );

    let _ = backend.cleanup(&harness);
}

#[test]
fn gleam_e2e_detect_project() {
    let backend = GleamBackend::new();
    let dir = tempfile::tempdir().unwrap();

    assert!(!backend.detect_project(dir.path()));

    std::fs::write(dir.path().join("gleam.toml"), "").unwrap();
    assert!(backend.detect_project(dir.path()));
}
